<!DOCTYPE HTML>
<html>
    <head>
        <title>Monte sua marmita</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'href' => $this->basePath() . '/img/favicon.png'
        ));

        // Instrui o Internet Explorer a utilizar a ultima versão disponível
        if (preg_match("/MSIE/", $_SERVER["HTTP_USER_AGENT"])) :
        ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <?php endif ?>
        <meta http-equiv="Content-Type"  content="text/html;charset=UTF-8"/>

    </head>
    <style>
        html, body {
            width:100%;
            height:100%;
            margin:0;
            padding:0;
        }
    </style>
    <body ng-app="app">
            <?php echo $this->content; ?>
    </body>
</html>
